import React, { useState } from 'react';

/**
 * FormatSelector Component
 * Allows users to select video format before generation
 * Format 1: Perfect UGC Hybrid (default) - Kling + Sora
 * Format 2: UGC Creative Kling - 100% Kling creative angles
 * Format 3-5: Coming Soon
 */

const formats = [
  {
    id: 'format_1',
    name: 'Perfect UGC Hybrid',
    icon: '🎤',
    secondaryIcon: '🎥',
    badge: '⭐ MOST POPULAR',
    badgeColor: 'bg-gradient-to-r from-yellow-500 to-amber-500',
    description: 'Talking head + b-roll scenes',
    fullDescription: 'Authentic talking-head UGC combined with professional product b-roll. Your avatar speaks directly to viewers explaining benefits, while lifestyle shots prove the product works. Perfect for traditional direct-response ads.',
    videoStyle: 'perfect_ugc_hybrid',
    active: true,
    features: [
      '✅ Avatar talking directly to camera',
      '✅ Creative b-roll for solution scenes',
      '✅ Natural, authentic feel',
      '✅ Proven conversion formula',
      '✅ 30-40 second videos'
    ],
    bestFor: 'Product explanations with demonstrations, problem-solution narratives, traditional direct-response ads',
    technicalDetails: {
      aiModels: 'Kling + Sora',
      duration: '30-40s',
      style: 'Professional UGC',
      scenes: 'Hook, Agitation, Solution, CTA'
    },
    stats: 'Avg. 3.2% CTR'
  },
  {
    id: 'format_2',
    name: 'Creative Kling',
    icon: '🎬',
    secondaryIcon: null,
    badge: '🎨 NEW',
    badgeColor: 'bg-gradient-to-r from-purple-500 to-pink-500',
    description: '100% creative POV angles',
    fullDescription: '100% creative visual storytelling with infinite camera angles. First-person POV, environmental proof, extreme close-ups, lifestyle integration. Every scene is visually unique and scroll-stopping. Made for viral TikTok content.',
    videoStyle: 'ugc_creative_kling',
    active: true,
    features: [
      '✅ First-person POV shots',
      '✅ Environmental context (product in snow, rain, etc.)',
      '✅ Extreme creative angles',
      '✅ Every scene visually different',
      '✅ 25-35 second videos'
    ],
    bestFor: 'Product showcases with visual impact, environment-driven storytelling, waterproof/outdoor products, TikTok viral-style content',
    technicalDetails: {
      aiModels: '100% Kling',
      duration: '25-35s',
      style: 'Ultra-creative',
      scenes: 'Creative POV + First-person angles'
    },
    stats: 'Ultra scroll-stopping'
  },
  {
    id: 'format_3',
    name: 'Cinematic Product Ads',
    icon: '🎬',
    secondaryIcon: '✨',
    badge: '⚡ FASTEST',
    badgeColor: 'bg-gradient-to-r from-cyan-500 to-blue-500',
    description: 'Pure cinematic product showcase',
    fullDescription: 'Skip the strategy, jump straight to stunning visuals. Just provide your product info and get a professional cinematic ad in minutes. Perfect for when you want beautiful product videos without the complexity of UGC storytelling.',
    videoStyle: 'cinematic',
    active: true,
    features: [
      '✅ No strategic analysis needed',
      '✅ Minimal questions (just product info)',
      '✅ Pure visual storytelling',
      '✅ Dramatic cinematography',
      '✅ 10-15 second videos'
    ],
    bestFor: 'Simple product showcases, e-commerce product videos, lifestyle brands, when you need quick turnaround without complex strategy',
    technicalDetails: {
      aiModels: 'KIE Sora 2 Pro',
      duration: '10-15s',
      style: 'Cinematic',
      scenes: 'Auto-generated by Claude'
    },
    stats: '⚡ Fastest generation'
  },
  {
    id: 'format_4',
    name: 'Coming Soon',
    icon: '🔜',
    secondaryIcon: null,
    badge: 'SOON',
    badgeColor: 'bg-gray-600',
    description: 'New format launching soon',
    fullDescription: 'More amazing formats are on the way! Stay tuned for exciting new video styles.',
    videoStyle: null,
    active: false,
    features: [],
    bestFor: '',
    technicalDetails: {},
    stats: ''
  },
  {
    id: 'format_5',
    name: 'Coming Soon',
    icon: '🔜',
    secondaryIcon: null,
    badge: 'SOON',
    badgeColor: 'bg-gray-600',
    description: 'New format launching soon',
    fullDescription: 'More amazing formats are on the way! Stay tuned for exciting new video styles.',
    videoStyle: null,
    active: false,
    features: [],
    bestFor: '',
    technicalDetails: {},
    stats: ''
  },
];

const FormatSelector = ({ onSelect, initialFormat = 'format_1' }) => {
  const [selectedFormat, setSelectedFormat] = useState(initialFormat);
  const [expandedFormat, setExpandedFormat] = useState(null);

  const handleSelect = (format) => {
    if (!format.active) return;
    console.log('[FormatSelector] 🎬 Format clicked:', format.name);
    console.log('[FormatSelector] 🎬 Video style:', format.videoStyle);
    console.log('[FormatSelector] 🎬 Format ID:', format.id);
    setSelectedFormat(format.id);
    if (onSelect) {
      console.log('[FormatSelector] 🎬 Calling onSelect with:', format.videoStyle, format.id);
      onSelect(format.videoStyle, format.id);
    }
  };

  const toggleExpand = (formatId) => {
    setExpandedFormat(expandedFormat === formatId ? null : formatId);
  };

  return (
    <div className="w-full">
      {/* Header */}
      <div className="mb-8 text-center">
        <h2 className="text-3xl font-bold text-white mb-3">
          🎬 Select Your Video Format
        </h2>
        <p className="text-gray-400 text-lg">
          Choose the style that best fits your product and marketing goals
        </p>
      </div>

      {/* Format Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
        {formats.map((format) => {
          const isSelected = selectedFormat === format.id;
          const isExpanded = expandedFormat === format.id;
          const isDisabled = !format.active;

          return (
            <div
              key={format.id}
              className={`
                relative rounded-xl border-2 transition-all duration-300 overflow-hidden
                ${isSelected && !isDisabled
                  ? 'border-purple-500 bg-gradient-to-br from-purple-900/30 to-pink-900/20 shadow-lg shadow-purple-500/20'
                  : isDisabled
                  ? 'border-gray-700 bg-gray-900/30 cursor-not-allowed opacity-50'
                  : 'border-[#262626] bg-[#1A1A1A] hover:border-purple-500/50 hover:shadow-lg hover:shadow-purple-500/10 cursor-pointer'
                }
                ${!isDisabled && 'hover:scale-105'}
              `}
              onClick={() => !isDisabled && handleSelect(format)}
            >
              {/* Badge */}
              <div className={`absolute top-3 right-3 px-3 py-1 rounded-full text-xs font-bold text-white ${format.badgeColor} z-10`}>
                {format.badge}
              </div>

              {/* Card Content */}
              <div className="p-6">
                {/* Icon */}
                <div className="flex items-center justify-center mb-4">
                  <div className="text-6xl">
                    {format.icon}
                    {format.secondaryIcon && (
                      <>
                        <span className="text-3xl mx-1 text-gray-500">+</span>
                        <span className="text-6xl">{format.secondaryIcon}</span>
                      </>
                    )}
                  </div>
                </div>

                {/* Title */}
                <h3 className="text-xl font-bold text-white mb-2 text-center">
                  {format.name}
                </h3>

                {/* Description */}
                <p className="text-gray-400 text-sm text-center mb-4">
                  {format.description}
                </p>

                {/* Stats (only for active formats) */}
                {format.active && format.stats && (
                  <div className="bg-black/30 rounded-lg px-3 py-2 mb-4 text-center">
                    <span className="text-purple-400 text-sm font-semibold">
                      {format.stats}
                    </span>
                  </div>
                )}

                {/* Technical Details (only for active formats) */}
                {format.active && format.technicalDetails.aiModels && (
                  <div className="space-y-1 mb-4 text-xs">
                    <div className="flex justify-between text-gray-500">
                      <span>AI Models:</span>
                      <span className="text-gray-300">{format.technicalDetails.aiModels}</span>
                    </div>
                    <div className="flex justify-between text-gray-500">
                      <span>Duration:</span>
                      <span className="text-gray-300">{format.technicalDetails.duration}</span>
                    </div>
                    <div className="flex justify-between text-gray-500">
                      <span>Style:</span>
                      <span className="text-gray-300">{format.technicalDetails.style}</span>
                    </div>
                  </div>
                )}

                {/* Expand/Learn More Button */}
                {format.active && (
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      toggleExpand(format.id);
                    }}
                    className="w-full py-2 mb-3 rounded-lg border border-gray-600 text-gray-300 hover:border-purple-500 hover:text-purple-400 transition-all text-sm font-medium"
                  >
                    {isExpanded ? '▼ Show Less' : '▶ Learn More'}
                  </button>
                )}

                {/* Select Button */}
                {format.active ? (
                  <button
                    onClick={() => handleSelect(format)}
                    className={`
                      w-full py-3 rounded-lg font-bold transition-all text-sm
                      ${isSelected
                        ? 'bg-gradient-to-r from-purple-600 to-pink-600 text-white shadow-lg'
                        : 'bg-gray-700 text-gray-200 hover:bg-purple-600'
                      }
                    `}
                  >
                    {isSelected ? '✓ Selected' : 'Select Format'}
                  </button>
                ) : (
                  <div className="w-full py-3 rounded-lg bg-gray-800 text-gray-500 text-center font-medium text-sm cursor-not-allowed">
                    Coming Soon
                  </div>
                )}

                {/* Expanded Details */}
                {isExpanded && format.active && (
                  <div className="mt-4 pt-4 border-t border-gray-700 space-y-3 text-sm">
                    {/* Full Description */}
                    <div>
                      <h4 className="text-purple-400 font-semibold mb-1">About:</h4>
                      <p className="text-gray-400 text-xs leading-relaxed">
                        {format.fullDescription}
                      </p>
                    </div>

                    {/* Features */}
                    <div>
                      <h4 className="text-purple-400 font-semibold mb-2">Features:</h4>
                      <div className="space-y-1">
                        {format.features.map((feature, idx) => (
                          <p key={idx} className="text-gray-400 text-xs">
                            {feature}
                          </p>
                        ))}
                      </div>
                    </div>

                    {/* Best For */}
                    <div>
                      <h4 className="text-purple-400 font-semibold mb-1">Best For:</h4>
                      <p className="text-gray-400 text-xs leading-relaxed">
                        {format.bestFor}
                      </p>
                    </div>
                  </div>
                )}
              </div>

              {/* Selected Indicator */}
              {isSelected && !isDisabled && (
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-purple-500 to-pink-500"></div>
              )}
            </div>
          );
        })}
      </div>

      {/* Info Box */}
      <div className="bg-blue-900/20 border border-blue-500/30 rounded-lg p-4 text-sm">
        <div className="flex items-start gap-3">
          <span className="text-2xl">💡</span>
          <div>
            <h4 className="text-blue-400 font-semibold mb-1">Pro Tip:</h4>
            <p className="text-gray-300">
              <strong>Perfect UGC Hybrid</strong> is recommended for most products and has the highest average conversion rate. 
              Choose <strong>Creative Kling</strong> when visual impact and environmental context are more important than explanation (e.g., outdoor gear, waterproof products).
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FormatSelector;

